In [1]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [2]:
# Paths
RAW_DATA = Path("../data/generated")
PROCESSED_DATA = Path("../data/processed")

In [3]:
# Load data
customers = pd.read_csv(RAW_DATA / "customers_data.csv")
sales = pd.read_csv(RAW_DATA / "sales_data.csv")
products = pd.read_csv(RAW_DATA / "products_data.csv")
marketing = pd.read_csv(RAW_DATA / "marketing_data.csv")

In [4]:
# Display data
display(customers.head())
display(sales.head())
display(products.head())
display(marketing.head())

,Customer_ID,Name,Age,Gender,Location,Join_Date,Churn,Total_Spent
0,2001,Allison Hill,45,Female,Jacksonville,2022-03-20,0,9757.66
1,2002,Noah Rhodes,50,Male,San Antonio,2023-10-05,0,10921.86
2,2003,Angie Henderson,63,Female,New York,2023-01-25,0,7032.84
3,2004,Daniel Wagner,52,Male,Philadelphia,2024-11-30,1,487.76
4,2005,Cristian Santos,60,Female,San Jose,2024-06-02,0,9999.42

,Sale_ID,Product_ID,Customer_ID,Date,Quantity,Sale_Price,Channel,Campaign_ID
0,1,197,2001,2025-05-28,1,270.16,Social,212
1,2,185,2001,2023-10-20,1,143.79,In-Store,108
2,3,124,2001,2025-04-13,4,174.26,Online,62
3,4,121,2001,2023-08-24,4,126.42,Online,32
4,5,170,2001,2023-05-20,4,124.94,Online,26

   Product_ID Product_Name  Category   Price    Brand
0         101    T-shirt 1  Clothing  116.40  Brand D
1         102      Boots 2  Footwear  175.20  Brand I
2         103     Blouse 3  Clothing   74.85  Brand A
3         104     Hoodie 4  Clothing   50.25  Brand J
4         105      Pants 5  Clothing   45.85  Brand I

,Campaign_ID,Channel,Start_Date,End_Date,Budget,Impressions,Clicks,Conversions
0,1,Online,2022-01-01,2022-02-06,6759.46,32951,2310,116
1,2,Online,2022-01-29,2022-02-21,5111.02,61775,1353,123
2,3,Online,2022-02-11,2022-03-19,6427.72,319487,11295,782
3,4,Online,2022-03-10,2022-03-30,9337.00,119438,7088,809
4,5,Online,2022-03-23,2022-05-07,6569.71,199229,10655,1225

In [5]:
# Shapes
print("Customers:", customers.shape)
print("Sales:", sales.shape)
print("Products:", products.shape)
print("Marketing:", marketing.shape)

Customers: (1000, 8)
Sales: (15741, 8)
Products: (100, 5)
Marketing: (366, 8)

In [6]:
# Info
customers.info()
sales.info()
products.info()
marketing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  1000 non-null   int64
 1   Name         1000 non-null   object
 2   Age          1000 non-null   int64
 3   Gender       1000 non-null   object
 4   Location     1000 non-null   object
 5   Join_Date    1000 non-null   object
 6   Churn        1000 non-null   int64
 7   Total_Spent  1000 non-null   float64
dtypes: float64(1), int64(3), object(4)
memory usage: 62.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15741 entries, 0 to 15740
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sale_ID      15741 non-null  int64
 1   Product_ID   15741 non-null  int64
 2   Customer_ID  15741 non-null  int64
 3   Date         15741 non-null  object
 4   Quantity     15741 non-null  int64
 5   Sale_Price   15741 non-null  float64
 6   Channel      15741 non-null  object
 7   Campaign_ID  15741 non-null  int64
dtypes: float64(1), int64(5), object(2)
memory usage: 983.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    100 non-null    int64
 1   Product_Name  100 non-null    object
 2   Category      100 non-null    object
 3   Price         100 non-null    float64
 4   Brand         100 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 4.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Campaign_ID  366 non-null    int64
 1   Channel      366 non-null    object
 2   Start_Date   366 non-null    object
 3   End_Date     366 non-null    object
 4   Budget       366 non-null    float64
 5   Impressions  366 non-null    int64
 6   Clicks       366 non-null    int64
 7   Conversions  366 non-null    int64
dtypes: float64(1), int64(4), object(3)
memory usage: 23.0+ KB

In [7]:
# Missing values
print("Customers")
print(customers.isnull().sum())

print("\nSales")
print(sales.isnull().sum())

print("\nProducts")
print(products.isnull().sum())

print("\nMarketing")
print(marketing.isnull().sum())

Customers
Customer_ID    0
Name           0
Age            0
Gender         0
Location       0
Join_Date      0
Churn          0
Total_Spent    0
dtype: int64

Sales
Sale_ID        0
Product_ID     0
Customer_ID    0
Date           0
Quantity       0
Sale_Price     0
Channel        0
Campaign_ID    0
dtype: int64

Products
Product_ID      0
Product_Name    0
Category        0
Price           0
Brand           0
dtype: int64

Marketing
Campaign_ID    0
Channel        0
Start_Date     0
End_Date       0
Budget         0
Impressions    0
Clicks         0
Conversions    0
dtype: int64

In [8]:
# Duplicates
print("Customers:", customers.duplicated().sum())
print("Sales:", sales.duplicated().sum())
print("Products:", products.duplicated().sum())
print("Marketing:", marketing.duplicated().sum())

Customers: 0
Sales: 0
Products: 0
Marketing: 0

In [9]:
# Statistics
display(customers.describe(include="all"))
display(sales.describe(include="all"))
display(products.describe(include="all"))
display(marketing.describe(include="all"))

,Customer_ID,Name,Age,Gender,Location,Join_Date,Churn,Total_Spent
count,1000.000000,1000,1000.000000,1000,1000,1000,1000.000000,1000.000000
unique,NaN,995,NaN,2,12,669,NaN,NaN
top,NaN,David Davis,NaN,Female,Dallas,2023-11-11,NaN,NaN
freq,NaN,2,NaN,525,100,5,NaN,NaN
mean,2500.500000,NaN,44.556000,NaN,NaN,NaN,0.408000,5553.870870
std,288.819436,NaN,14.976019,NaN,NaN,NaN,0.491709,4064.221665
min,2001.000000,NaN,18.000000,NaN,NaN,NaN,0.000000,27.080000
25%,2250.750000,NaN,32.000000,NaN,NaN,NaN,0.000000,1475.352500
50%,2500.500000,NaN,45.000000,NaN,NaN,NaN,0.000000,5715.215000
75%,2750.250000,NaN,57.250000,NaN,NaN,NaN,1.000000,8739.757500
max,3000.000000,NaN,70.000000,NaN,NaN,NaN,1.000000,16856.640000

,Sale_ID,Product_ID,Customer_ID,Date,Quantity,Sale_Price,Channel,Campaign_ID
count,15741.000000,15741.000000,15741.00000,15741,15741.000000,15741.000000,15741,15741.000000
unique,NaN,NaN,NaN,1366,NaN,NaN,5,NaN
top,NaN,NaN,NaN,2024-11-09,NaN,NaN,Online,NaN
freq,NaN,NaN,NaN,31,NaN,NaN,8660,NaN
mean,7871.000000,149.915063,2502.72416,NaN,2.864685,120.875240,NaN,108.934502
std,4544.179629,28.959229,290.09092,NaN,1.378261,68.562446,NaN,84.260265
min,1.000000,101.000000,2001.00000,NaN,1.000000,12.930000,NaN,1.000000
25%,3936.000000,124.000000,2250.00000,NaN,2.000000,70.100000,NaN,49.000000
50%,7871.000000,150.000000,2506.00000,NaN,3.000000,120.250000,NaN,70.000000
75%,11806.000000,175.000000,2754.00000,NaN,4.000000,161.440000,NaN,140.000000
max,15741.000000,200.000000,3000.00000,NaN,5.000000,298.930000,NaN,366.000000

        Product_ID Product_Name  Category       Price    Brand
count   100.000000          100       100  100.000000      100
unique         NaN          100         4         NaN       10
top            NaN    T-shirt 1  Clothing         NaN  Brand D
freq           NaN            1        32         NaN       13
mean    150.500000          NaN       NaN  113.909900      NaN
std      29.011492          NaN       NaN   67.412463      NaN
min     101.000000          NaN       NaN   12.930000      NaN
25%     125.750000          NaN       NaN   68.662500      NaN
50%     150.500000          NaN       NaN  110.100000      NaN
75%     175.250000          NaN       NaN  147.530000      NaN
max     200.000000          NaN       NaN  298.930000      NaN

,Campaign_ID,Channel,Start_Date,End_Date,Budget,Impressions,Clicks,Conversions
count,366.000000,366,366,366,366.000000,366.000000,366.000000,366.000000
unique,NaN,5,335,327,NaN,NaN,NaN,NaN
top,NaN,Online,2022-01-01,2026-01-15,NaN,NaN,NaN,NaN
freq,NaN,77,5,4,NaN,NaN,NaN,NaN
mean,183.500000,NaN,NaN,NaN,5365.699180,243326.767760,11733.035519,1027.008197
std,105.799338,NaN,NaN,NaN,2630.841688,143105.547209,11029.560571,1268.892611
min,1.000000,NaN,NaN,NaN,501.750000,10102.000000,130.000000,5.000000
25%,92.250000,NaN,NaN,NaN,3048.512500,117639.000000,3552.500000,176.250000
50%,183.500000,NaN,NaN,NaN,5493.635000,247588.500000,8028.500000,618.000000
75%,274.750000,NaN,NaN,NaN,7550.610000,361012.000000,15793.000000,1420.500000
max,366.000000,NaN,NaN,NaN,9939.060000,498813.000000,59703.000000,9228.000000

In [10]:
# Convert dates
customers["Join_Date"] = pd.to_datetime(customers["Join_Date"])
sales["Date"] = pd.to_datetime(sales["Date"])
marketing["Start_Date"] = pd.to_datetime(marketing["Start_Date"])
marketing["End_Date"] = pd.to_datetime(marketing["End_Date"])

In [11]:
# Check dates
print(customers.dtypes)
print(sales.dtypes)
print(marketing.dtypes)

Customer_ID             int64
Name                   object
Age                     int64
Gender                 object
Location               object
Join_Date      datetime64[ns]
Churn                   int64
Total_Spent           float64
dtype: object
Sale_ID                 int64
Product_ID              int64
Customer_ID             int64
Date           datetime64[ns]
Quantity                int64
Sale_Price            float64
Channel                object
Campaign_ID             int64
dtype: object
Campaign_ID             int64
Channel                object
Start_Date     datetime64[ns]
End_Date       datetime64[ns]
Budget                float64
Impressions             int64
Clicks                  int64
Conversions             int64
dtype: object

In [12]:
# Validate customers
print("Age min:", customers["Age"].min())
print("Age max:", customers["Age"].max())
print("Spent min:", customers["Total_Spent"].min())

Age min: 18
Age max: 70
Spent min: 27.08

In [13]:
# Validate sales
print("Quantity min:", sales["Quantity"].min())
print("Sale price min:", sales["Sale_Price"].min())
print("Channels:", sales["Channel"].unique())

Quantity min: 1
Sale price min: 12.93
Channels: ['Social' 'In-Store' 'Online' 'Email' 'TV']

In [14]:
# Validate products
print("Price min:", products["Price"].min())
print("Categories:", products["Category"].unique())
print("Brands:", products["Brand"].unique())

Price min: 12.93
Categories: ['Clothing' 'Footwear' 'Accessories' 'Outerwear']
Brands: ['Brand D' 'Brand I' 'Brand A' 'Brand J' 'Brand E' 'Brand F' 'Brand G'
 'Brand B' 'Brand H' 'Brand C']

In [15]:
# Validate marketing
print("Budget min:", marketing["Budget"].min())
print("Impressions min:", marketing["Impressions"].min())
print("Clicks min:", marketing["Clicks"].min())
print("Conversions min:", marketing["Conversions"].min())

Budget min: 501.75
Impressions min: 10102
Clicks min: 130
Conversions min: 5

In [16]:
# Check customer references
print(
    sales["Customer_ID"].isin(customers["Customer_ID"])
)

0        True
1        True
2        True
3        True
4        True
         ...
15736    True
15737    True
15738    True
15739    True
15740    True
Name: Customer_ID, Length: 15741, dtype: bool

In [17]:
# Check product references
print(
    sales["Product_ID"].isin(products["Product_ID"])
)

0        True
1        True
2        True
3        True
4        True
         ...
15736    True
15737    True
15738    True
15739    True
15740    True
Name: Product_ID, Length: 15741, dtype: bool

In [18]:
# Check campaign consistency
print(
    (marketing["Conversions"] <= marketing["Clicks"]).all()
)

print(
    (marketing["Clicks"] <= marketing["Impressions"]).all()
)

True
True

In [19]:
# Check campaign dates
print(
    (marketing["Start_Date"] <= marketing["End_Date"]).all()
)

True

In [20]:
# Calculate revenue
sales["Revenue"] = sales["Sale_Price"]

# Display revenue
display(sales)

,Sale_ID,Product_ID,Customer_ID,Date,Quantity,Sale_Price,Channel,Campaign_ID,Revenue
0,1,197,2001,2025-05-28,1,270.16,Social,212,270.16
1,2,185,2001,2023-10-20,1,143.79,In-Store,108,143.79
2,3,124,2001,2025-04-13,4,174.26,Online,62,174.26
3,4,121,2001,2023-08-24,4,126.42,Online,32,126.42
4,5,170,2001,2023-05-20,4,124.94,Online,26,124.94
...,...,...,...,...,...,...,...,...,...
15736,15737,147,3000,2025-10-20,3,193.11,Online,72,193.11
15737,15738,125,3000,2025-06-29,1,25.35,Social,214,25.35
15738,15739,185,3000,2025-06-12,5,143.79,Online,65,143.79
15739,15740,197,3000,2025-11-25,5,270.16,Online,75,270.16
15740,15741,112,3000,2025-04-05,3,58.11,Email,284,58.11

In [21]:
# Total revenue
print("Total revenue:", sales["Revenue"].sum())

Total revenue: 1902697.1600000001

In [22]:
# Comparer les prix
sales_products = sales.merge(
    products[["Product_ID", "Price"]],
    on="Product_ID",
    how="left"
)

display(sales_products[[
    "Product_ID",
    "Quantity",
    "Sale_Price",
    "Price"
]])

       Product_ID  Quantity  Sale_Price   Price
0             197         1      270.16  270.16
1             185         1      143.79  143.79
2             124         4      174.26  174.26
3             121         4      126.42  126.42
4             170         4      124.94  124.94
...           ...       ...         ...     ...
15736         147         3      193.11  193.11
15737         125         1       25.35   25.35
15738         185         5      143.79  143.79
15739         197         5      270.16  270.16
15740         112         3       58.11   58.11

[15741 rows x 4 columns]

In [23]:
# Vérifier les prix
sales_products["Expected_Total"] = (
    sales_products["Quantity"] * sales_products["Price"]
)

sales_products["Price_Consistent"] = (
    sales_products["Sale_Price"] == sales_products["Expected_Total"]
)

display(sales_products)
print(
    "Prix conformes :",
    sales_products["Price_Consistent"].sum(),
    "/",
    len(sales_products)
)

,Sale_ID,Product_ID,Customer_ID,Date,Quantity,Sale_Price,Channel,Campaign_ID,Revenue,Price,Expected_Total,Price_Consistent
0,1,197,2001,2025-05-28,1,270.16,Social,212,270.16,270.16,270.16,True
1,2,185,2001,2023-10-20,1,143.79,In-Store,108,143.79,143.79,143.79,True
2,3,124,2001,2025-04-13,4,174.26,Online,62,174.26,174.26,697.04,False
3,4,121,2001,2023-08-24,4,126.42,Online,32,126.42,126.42,505.68,False
4,5,170,2001,2023-05-20,4,124.94,Online,26,124.94,124.94,499.76,False
...,...,...,...,...,...,...,...,...,...,...,...,...
15736,15737,147,3000,2025-10-20,3,193.11,Online,72,193.11,193.11,579.33,False
15737,15738,125,3000,2025-06-29,1,25.35,Social,214,25.35,25.35,25.35,True
15738,15739,185,3000,2025-06-12,5,143.79,Online,65,143.79,143.79,718.95,False
15739,15740,197,3000,2025-11-25,5,270.16,Online,75,270.16,270.16,1350.80,False
15740,15741,112,3000,2025-04-05,3,58.11,Email,284,58.11,58.11,174.33,False

Prix conformes : 3416 / 15741

In [24]:
# Vérifier les écarts
sales_products["Expected_Total"] = (
    sales_products["Quantity"] * sales_products["Price"]
)

display(sales_products)

,Sale_ID,Product_ID,Customer_ID,Date,Quantity,Sale_Price,Channel,Campaign_ID,Revenue,Price,Expected_Total,Price_Consistent
0,1,197,2001,2025-05-28,1,270.16,Social,212,270.16,270.16,270.16,True
1,2,185,2001,2023-10-20,1,143.79,In-Store,108,143.79,143.79,143.79,True
2,3,124,2001,2025-04-13,4,174.26,Online,62,174.26,174.26,697.04,False
3,4,121,2001,2023-08-24,4,126.42,Online,32,126.42,126.42,505.68,False
4,5,170,2001,2023-05-20,4,124.94,Online,26,124.94,124.94,499.76,False
...,...,...,...,...,...,...,...,...,...,...,...,...
15736,15737,147,3000,2025-10-20,3,193.11,Online,72,193.11,193.11,579.33,False
15737,15738,125,3000,2025-06-29,1,25.35,Social,214,25.35,25.35,25.35,True
15738,15739,185,3000,2025-06-12,5,143.79,Online,65,143.79,143.79,718.95,False
15739,15740,197,3000,2025-11-25,5,270.16,Online,75,270.16,270.16,1350.80,False
15740,15741,112,3000,2025-04-05,3,58.11,Email,284,58.11,58.11,174.33,False

In [25]:
# Jointure ventes-produits
sales_full = sales.merge(
    products,
    on="Product_ID",
    how="left"
)

# Jointure clients-ventes
sales_full = sales_full.merge(
    customers,
    on="Customer_ID",
    how="left"
)

display(sales_full)

,Sale_ID,Product_ID,Customer_ID,Date,Quantity,Sale_Price,Channel,Campaign_ID,Revenue,Product_Name,Category,Price,Brand,Name,Age,Gender,Location,Join_Date,Churn,Total_Spent
0,1,197,2001,2025-05-28,1,270.16,Social,212,270.16,Blazer 97,Outerwear,270.16,Brand E,Allison Hill,45,Female,Jacksonville,2022-03-20,0,9757.66
1,2,185,2001,2023-10-20,1,143.79,In-Store,108,143.79,Running Shoes 85,Footwear,143.79,Brand G,Allison Hill,45,Female,Jacksonville,2022-03-20,0,9757.66
2,3,124,2001,2025-04-13,4,174.26,Online,62,174.26,Windbreaker 24,Outerwear,174.26,Brand J,Allison Hill,45,Female,Jacksonville,2022-03-20,0,9757.66
3,4,121,2001,2023-08-24,4,126.42,Online,32,126.42,Jacket 21,Outerwear,126.42,Brand J,Allison Hill,45,Female,Jacksonville,2022-03-20,0,9757.66
4,5,170,2001,2023-05-20,4,124.94,Online,26,124.94,Blazer 70,Outerwear,124.94,Brand F,Allison Hill,45,Female,Jacksonville,2022-03-20,0,9757.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15736,15737,147,3000,2025-10-20,3,193.11,Online,72,193.11,Jacket 47,Outerwear,193.11,Brand E,Elizabeth Sanders,59,Female,Los Angeles,2023-08-03,0,10200.96
15737,15738,125,3000,2025-06-29,1,25.35,Social,214,25.35,Handbag 25,Accessories,25.35,Brand C,Elizabeth Sanders,59,Female,Los Angeles,2023-08-03,0,10200.96
15738,15739,185,3000,2025-06-12,5,143.79,Online,65,143.79,Running Shoes 85,Footwear,143.79,Brand G,Elizabeth Sanders,59,Female,Los Angeles,2023-08-03,0,10200.96
15739,15740,197,3000,2025-11-25,5,270.16,Online,75,270.16,Blazer 97,Outerwear,270.16,Brand E,Elizabeth Sanders,59,Female,Los Angeles,2023-08-03,0,10200.96
15740,15741,112,3000,2025-04-05,3,58.11,Email,284,58.11,Pants 12,Clothing,58.11,Brand J,Elizabeth Sanders,59,Female,Los Angeles,2023-08-03,0,10200.96

In [26]:
# Save cleaned data
customers.to_csv(
    PROCESSED_DATA / "customers_data.csv",
    index=False
)

sales.to_csv(
    PROCESSED_DATA / "sales_data.csv",
    index=False
)

products.to_csv(
    PROCESSED_DATA / "products_data.csv",
    index=False
)

marketing.to_csv(
    PROCESSED_DATA / "marketing_data.csv",
    index=False
)

In [27]:
# Statistiques clients
customer_analytics = sales_full.groupby("Customer_ID").agg(
    Number_Of_Purchases=("Sale_ID", "count"),
    Total_Quantity=("Quantity", "sum"),
    Sales_Revenue=("Revenue", "sum"),
    Average_Purchase=("Revenue", "mean")
).reset_index()

display(customer_analytics)

,Customer_ID,Number_Of_Purchases,Total_Quantity,Sales_Revenue,Average_Purchase
0,2001,26,84,3332.54,128.174615
1,2002,26,82,3647.68,140.295385
2,2003,23,61,2658.59,115.590870
3,2004,3,7,229.50,76.500000
4,2005,21,78,2726.18,129.818095
...,...,...,...,...,...
995,2996,18,46,2833.76,157.431111
996,2997,5,10,427.32,85.464000
997,2998,18,53,2088.61,116.033889
998,2999,7,14,568.99,81.284286
999,3000,20,67,2785.32,139.266000

In [28]:
# Informations clients
customer_analytics = customer_analytics.merge(
    customers[
        ["Customer_ID", "Age", "Gender", "Location", "Join_Date", "Total_Spent"]
    ],
    on="Customer_ID",
    how="left"
)

display(customer_analytics)

,Customer_ID,Number_Of_Purchases,Total_Quantity,Sales_Revenue,Average_Purchase,Age,Gender,Location,Join_Date,Total_Spent
0,2001,26,84,3332.54,128.174615,45,Female,Jacksonville,2022-03-20,9757.66
1,2002,26,82,3647.68,140.295385,50,Male,San Antonio,2023-10-05,10921.86
2,2003,23,61,2658.59,115.590870,63,Female,New York,2023-01-25,7032.84
3,2004,3,7,229.50,76.500000,52,Male,Philadelphia,2024-11-30,487.76
4,2005,21,78,2726.18,129.818095,60,Female,San Jose,2024-06-02,9999.42
...,...,...,...,...,...,...,...,...,...,...
995,2996,18,46,2833.76,157.431111,67,Female,Jacksonville,2024-01-22,6740.30
996,2997,5,10,427.32,85.464000,57,Female,San Jose,2023-01-15,866.41
997,2998,18,53,2088.61,116.033889,22,Female,Houston,2023-05-05,6441.92
998,2999,7,14,568.99,81.284286,67,Male,San Jose,2024-12-09,1105.17
999,3000,20,67,2785.32,139.266000,59,Female,Los Angeles,2023-08-03,10200.96

In [29]:
# Sauvegarder
customer_analytics.to_csv(
    PROCESSED_DATA / "customer_analytics.csv",
    index=False
)